# Generated by Django 4.2.1 on 2023-07-26 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_project', '0003_favoritehotel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritehotel',
            old_name='hotel_id',
            new_name='hotelId',
        ),
        migrations.RenameField(
            model_name='favoritehotel',
            old_name='hotel_name',
            new_name='hotelName',
        ),
        migrations.RenameField(
            model_name='favoritehotel',
            old_name='img_url',
            new_name='imgUrl',
        ),
    ]
